/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/INeUsF2qdcV
 */
import { Label } from "./ui/label";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { Button } from "./ui/button";
import { Card } from "./ui/card";
import { useForm, SubmitHandler } from "react-hook-form";

interface Inputs {
  name: string;
  email: string;
  message: string;
}

export function GuestBook() {
  const { register, handleSubmit } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = (data) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <div className="flex flex-col min-h-screen">
        <header className="bg-zinc-700 dark:bg-zinc-800 text-white w-full py-4">
          <h2 className="text-center text-2xl font-bold">
            Welcome to Our Website
          </h2>
        </header>
        <main className="max-w-4xl mx-auto p-4 space-y-8 flex-grow flex flex-col items-center justify-center">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold text-center">Guest Book</h1>
            <p className="text-zinc-500 dark:text-zinc-400 text-center">
              We would love to hear from you. Please sign our guest book.
            </p>
          </div>
          <Card className="p-6 space-y-4 w-full max-w-xl">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input placeholder="Enter your name" {...register("name")} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input placeholder="Enter your email" {...register("email")} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="message">Message</Label>
              <Textarea
                className="min-h-[100px]"
                placeholder="Enter your message"
                {...register("message")}
              />
            </div>
            <div className="flex justify-end">
              <Button type="submit">Sign Guest Book</Button>
            </div>
          </Card>
          <div className="w-full max-w-xl grid grid-cols-2 gap-4">
            <Card className="p-4">
              <h3 className="text-lg font-bold">John Doe</h3>
              <p className="text-zinc-500 dark:text-zinc-400">
                johndoe@example.com
              </p>
              <p>Lovely website! Keep up the good work.</p>
            </Card>
            <Card className="p-4">
              <h3 className="text-lg font-bold">Jane Doe</h3>
              <p className="text-zinc-500 dark:text-zinc-400">
                janedoe@example.com
              </p>
              <p>Amazing website! I enjoyed my visit.</p>
            </Card>
          </div>
        </main>
        <footer className="bg-zinc-700 dark:bg-zinc-800 text-white w-full py-4 mt-auto">
          <h3 className="text-center text-2xl font-bold">
            Thank You for Visiting
          </h3>
        </footer>
      </div>
    </form>
  );
}
